Update retry

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -257,3 +257,58 @@ jobs:
       - setup-matrix
       - setup-inputs
       - build-jail
+
+  # Restart the scheduled run when it failed
+  # https://www.eliostruyf.com/restart-github-actions-workflow-failed/
+  restart_build-base:
+    runs-on: ubuntu-latest
+    if: github.event_name == 'schedule' && failure()
+    needs:
+      - build-base
+      - build-web
+      - build-jail
+
+    steps:
+
+      - 
+        name: Retry the workflow
+        run: |
+
+          WORKFLOWS_URL="/repos/${{ github.repository }}/"
+          WORKFLOWS_URL+="actions/workflows"
+          echo "$WORKFLOWS_URL"
+  
+          WORKFLOWS_JSON=$(gh api \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" ${WORKFLOWS_URL} || echo "")
+          echo "$WORKFLOWS_JSON"
+
+          # If list of workflows does not exist just fail
+          if [[ -z "${WORKFLOWS_JSON}" ]];
+          then
+            exit 1
+          fi
+
+          # Get workflow id
+          WORKFLOW_ID=`echo $WORKFLOWS_JSON | \
+            jq --arg var "${{ github.workflow }}" \
+              '.workflows[] | select(.name == $var) | .id'`
+          echo $WORKFLOW_ID
+
+          # Wait 60s before restarting
+          sleep 60s
+
+          curl -L \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/${{ github.repository }}/actions/\
+            workflows/$WORKFLOW_ID/dispatches \
+            -d '{"ref":"${{ github.ref }}", \
+              "inputs":{ \
+                "tags":"${{ inputs.tags }}", \
+                "latest":"${{ inputs.latest }}", \
+                "ref":"${{ inputs.ref }}"}}'
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
