Update ghcr-docker-delete-deprecated.yml

diff --git a/.github/workflows/ghcr-docker-delete-deprecated.yml b/.github/workflows/ghcr-docker-delete-deprecated.yml
--- a/.github/workflows/ghcr-docker-delete-deprecated.yml
+++ b/.github/workflows/ghcr-docker-delete-deprecated.yml
@@ -104,7 +104,7 @@ jobs:
       matrix:
         image:
           - boca-web
-          # - boca-jail
+          - boca-jail
     needs: setup
 
     steps:
@@ -130,6 +130,7 @@ jobs:
           RELEASES=$(echo $RELEASES | tr -d "[]|\"")
           # Split string into an array
           IFS=', ' read -r -a RELEASES <<< "$RELEASES"
+          echo "${RELEASES[@]}"
 
           # Unset variable
           unset DIGESTKEYS
@@ -182,12 +183,24 @@ jobs:
       - 
         name: Delete untagged Docker images on ghcr.io
         uses: actions/delete-package-versions@v4
+        if: ${{ env.digest_keys != '' }}
         with:
           package-name: '${{ env.package_name }}/${{ matrix.image }}'
           package-type: 'container'
           delete-only-untagged-versions: 'true'
           ignore-versions: '${{ env.digest_keys }}'
           token: ${{ secrets.GITHUB_TOKEN }}
+
+      # Necessary if testing locally with 'act'
+      # https://github.com/nektos/act
+
+      # Install GH CLI (self-hosted runners do not come with it out of the box)
+      # https://github.com/dev-hanz-ops/install-gh-cli-action
+      # - 
+      #   name: Install GH CLI
+      #   uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
+      #   with:
+      #     gh-cli-version: 2.14.2 # optional, see action.yml for current default
 
       - 
         name: Compile unsupported releases
@@ -197,16 +210,15 @@ jobs:
           RELEASES=${{ toJSON(needs.setup.outputs.release) }}
           # Remove square brackets and double quotes
           RELEASES=$(echo $RELEASES | tr -d "[]|\"")
-          echo $RELEASES
           # Split string into an array
           IFS=', ' read -r -a RELEASES <<< "$RELEASES"
+          echo "${RELEASES[@]}"
 
           # Set image
           IMG=${{ env.REGISTRY_HOST }}/${{ env.REPOSITORY_NAME }}/${{ matrix.image }}
 
           # Get all releases/tags
           ALLRELEASES=$(crane ls ${IMG} || echo "")
-          echo $ALLRELEASES
           # If list of tags is empty just skip it
           if [ -z "${ALLRELEASES}" ];
           then
@@ -217,6 +229,7 @@ jobs:
           ALLRELEASES=$(echo $ALLRELEASES | tr -d "\n\t\r|\"")
           # Split string into an array
           IFS=', ' read -r -a ALLRELEASES <<< "$ALLRELEASES"
+          echo "${ALLRELEASES[@]}"
 
           # Get unsupported releases
           DEPRECATED=()
@@ -228,45 +241,68 @@ jobs:
               [[ -n $skip ]] || DEPRECATED+=("$i")
           done
           declare -p DEPRECATED
+          echo "${DEPRECATED[@]}"
 
-          echo $(IFS=, ; echo "${DEPRECATED[*]}")
+          PACKAGE=${{ env.package_name }}
+          ENCODED_PACKAGE="${PACKAGE}/${{ matrix.image }}"
+          # Replace '/' with '%2F'
+          ENCODED_PACKAGE="${ENCODED_PACKAGE//\//\%2F}"
+          echo $ENCODED_PACKAGE
+
+          PACKAGESJSON=$(gh api \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            /users/${{ env.OWNER_NAME }}/packages/container/${ENCODED_PACKAGE}/versions || echo "")
+          echo $PACKAGESJSON
+
+          # If list of package versions does not exist just fail
+          if [ -z "${PACKAGESJSON}" ];
+          then
+            exit 1
+          fi
+
+          # Unset variable
+          unset VERSIONIDS
 
           # Iterate over releases to get digests
           for version in ${DEPRECATED[@]}
           do
             echo "${version}"
 
-            # If manifest does not exist just skip image
-            MANIFEST=$(crane manifest ${IMG}:${version} || echo "")
-            if [ -z "${MANIFEST}" ];
-            then
-              continue
-            fi
-
-            # Get digest key(s) of regular image (if not multi-arch)
-            DIGESTKEYS="${DIGESTKEYS} \
-              `crane manifest ${IMG}:${version} | \
-                jq 'select (.config != null) | .config.digest'`"
-            # or of multi-platform images builds
-            DIGESTKEYS="${DIGESTKEYS} \
-              `crane manifest ${IMG}:${version} | \
-                jq 'select (.manifests != null) | .manifests[].digest'`"
+            VERSIONIDS="${VERSIONIDS} \
+              `echo $PACKAGESJSON | \
+                jq --arg var $version \
+                  '.[] | select(any(.metadata.container.tags[]; contains ($var))) | .id'`"
           done
 
           # Remove newlines, tabs, carriage returns and double quotes
-          DIGESTKEYS=$(echo $DIGESTKEYS | tr -d "\n\t\r|\"")
+          VERSIONIDS=$(echo ${VERSIONIDS} | tr -d "\n\t\r|\"")
           # Replace white spaces with ', '
-          DIGESTKEYS="${DIGESTKEYS// /, }"
-          echo $DIGESTKEYS
+          VERSIONIDS="${VERSIONIDS// /, }"
+          # Split string into an array
+          IFS=', ' read -r -a VERSIONIDS <<< "$VERSIONIDS"
+          echo "${VERSIONIDS[@]}"
 
+          # Keep unique version ids only
+          UNIQIDS=($(printf "%s\n" "${VERSIONIDS[@]}" | sort -u))
+          echo "${UNIQIDS[@]}"
+
+          # Convert to string
+          UNIQSTR=$(echo $(IFS=, ; echo "${UNIQIDS[*]}"))
+          # Add white space after ','
+          UNIQSTR="${UNIQSTR//,/, }"
+          echo $UNIQSTR
           # Passing env variable between steps
-          echo "digest_keys=${DIGESTKEYS}" >> $GITHUB_ENV
+          echo "version_ids=${UNIQSTR}" >> $GITHUB_ENV
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - 
         name: Delete multiple specific Docker images on ghcr.io
         uses: actions/delete-package-versions@v4.1.0
+        if: ${{ env.version_ids != '' }}
         with:
-          package-version-ids: '${{ env.digest_keys }}'
+          package-version-ids: '${{ env.version_ids }}'
           package-name: '${{ env.package_name }}/${{ matrix.image }}'
           package-type: 'container'
           token: ${{ secrets.GITHUB_TOKEN }}
